included:
  - Sources
  - Tests

excluded:
  - .build
  - .git
  - Package.swift

disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - empty_string

line_length:
  warning: 140
  error: 200

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000
